# @package _global_
defaults:
  - _self_
embodied_task:
  name: spoc_env_testing
  episode_root: /home/ubuntu/jhu-scai-lab/yyin34/spoc/data/spoc_trajectories_val
  close_enough_distance: 1.2
  alignment_threshold: 20 # degrees allowed between agent heading and object center
  max_steps: 25
  trajectory:
    save: True
    save_path: /home/ubuntu/jhu-scai-lab/yyin34/spoc/data/env_testing
    image_keys: ['rgb']
    string_keys: ['action', 'position', 'rotation', 'distance_to_goal', 'distance_traveled', 'angle_turned']

agent:
  name: spoc_env_testing_agent
  camera:
    h: 240
    w: 240
    fx: 256
    fy: 256
    cx: 120
    cy: 120
    near: 0.1
    far: 10.0
  occupancy:
    resolution: 0.05
    obstacle_height_thresh: 0.2
    origin: [-5.0, -5.0, 0.0]
  