name: "dl3dv"
overfit_to_index: null
lindisp: false
viz_type: "interpolation"
dist_loss_weight: 0.005
depth_loss_weight: 1.0
depth_mask_loss_weight: 0.0
depth_smooth_loss_weight: 0.002
semantic_loss_weight: 0.1
semantic_reg_loss_weight: 0.1
lpips_loss_weight: 1.0
repa_loss_weight: 5.0
rgb_loss_weight: 1.
intermediate_weight: 2.0
vggt_alignment_loss_weight: 0.1
root_dir: ""
