defaults:
  - _self_

_target_: wm_baselines.world_model.oracle_depth_model.OracleDepthModel

name: oracle_depth_model

camera:
  _target_: wm_baselines.agent.perception.camera.Camera
  h: 240
  w: 240
  fx: 256
  fy: 256
  cx: 120
  cy: 120
  near: 0.1
  far: 10.0

model:
  _target_: wm_baselines.agent.perception.reconstruction.TSDFFusion
  _convert_: all
  K:
    - - 256
      - 0
      - 120
    - - 0
      - 256
      - 120
    - - 0
      - 0
      - 1
  width: 240
  height: 240
  voxel_length: 0.01
  sdf_trunc: 0.04
  depth_scale: 1.0
  depth_trunc: 10.0
  integrate_color: True
  device: CPU:0
  # block_resolution: 16
  # block_count: 120000

obs_occupancy:
  _target_: wm_baselines.agent.perception.occupancy.OccupancyMap
  resolution: 0.1
  obstacle_height_thresh: -0.1
  ceiling_height: 1.0 # w.r.t. agent height
  max_range: 3.0

adjacent_angle: 0.523599  # 30 degrees
adjacent_distance: 1.0  # meters