defaults:
  - _self_

_target_: belief_baselines.planner.cem_planner.CEMPlanner

name: cem_planner

vlm:
  _target_: belief_baselines.agent.vlm.vlm.VLM
  vlm_model_name: "gpt-5"

horizon: 5
num_sequences: 10
move_step: 0.3
rotation_step: 10.0