defaults:
  - _self_

_target_: wm_baselines.planner.exploration_planner.ExplorationPlanner

name: exploration_planner

goal_sampling_strategy: frontier
path_planning_algorithm: astar
action_name: nav_to
adjacent_angle: 1.57  # 90 degrees
adjacent_distance: 3.0  # meters